import Head from "next/head";
import Cards from "./Cards/Cards";
export default function Home() {
  return (
    <div>
      <Head>
        <title>RoboHash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://robohash.org/Thor?size=180x180" />
      </Head>
      <Cards />
    </div>
  );
}
